/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GroceryItem = IDL.Record({
  'checked' : IDL.Bool,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HealthGoal = IDL.Variant({
  'gainMuscle' : IDL.Null,
  'maintainWeight' : IDL.Null,
  'eatHealthier' : IDL.Null,
  'loseWeight' : IDL.Null,
});
export const MacroRatio = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'protein' : IDL.Nat,
});
export const DietType = IDL.Variant({
  'vegan' : IDL.Null,
  'omnivore' : IDL.Null,
  'keto' : IDL.Null,
  'paleo' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'healthGoal' : HealthGoal,
  'calorieTarget' : IDL.Nat,
  'macroRatio' : MacroRatio,
  'favoriteFoods' : IDL.Vec(IDL.Text),
  'dietType' : DietType,
  'allergies' : IDL.Vec(IDL.Text),
});
export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const Meal = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'prepTime' : IDL.Nat,
  'ingredients' : IDL.Vec(Ingredient),
  'protein' : IDL.Nat,
});
export const DayMeals = IDL.Record({
  'breakfast' : Meal,
  'lunch' : Meal,
  'snacks' : IDL.Vec(Meal),
  'dinner' : Meal,
});
export const MealPlan = IDL.Record({ 'days' : IDL.Vec(DayMeals) });
export const NutritionLog = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'protein' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGroceryItem' : IDL.Func([GroceryItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateMealPlan' : IDL.Func([IDL.Text, IDL.Vec(Header)], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroceryList' : IDL.Func([], [IDL.Vec(GroceryItem)], ['query']),
  'getMealPlan' : IDL.Func([], [IDL.Opt(MealPlan)], ['query']),
  'getNutritionLog' : IDL.Func([], [NutritionLog], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logNutrition' : IDL.Func([NutritionLog], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMealPlan' : IDL.Func([MealPlan], [], []),
  'toggleGroceryItemChecked' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GroceryItem = IDL.Record({
    'checked' : IDL.Bool,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HealthGoal = IDL.Variant({
    'gainMuscle' : IDL.Null,
    'maintainWeight' : IDL.Null,
    'eatHealthier' : IDL.Null,
    'loseWeight' : IDL.Null,
  });
  const MacroRatio = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  const DietType = IDL.Variant({
    'vegan' : IDL.Null,
    'omnivore' : IDL.Null,
    'keto' : IDL.Null,
    'paleo' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'healthGoal' : HealthGoal,
    'calorieTarget' : IDL.Nat,
    'macroRatio' : MacroRatio,
    'favoriteFoods' : IDL.Vec(IDL.Text),
    'dietType' : DietType,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const Ingredient = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Meal = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'prepTime' : IDL.Nat,
    'ingredients' : IDL.Vec(Ingredient),
    'protein' : IDL.Nat,
  });
  const DayMeals = IDL.Record({
    'breakfast' : Meal,
    'lunch' : Meal,
    'snacks' : IDL.Vec(Meal),
    'dinner' : Meal,
  });
  const MealPlan = IDL.Record({ 'days' : IDL.Vec(DayMeals) });
  const NutritionLog = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGroceryItem' : IDL.Func([GroceryItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateMealPlan' : IDL.Func([IDL.Text, IDL.Vec(Header)], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroceryList' : IDL.Func([], [IDL.Vec(GroceryItem)], ['query']),
    'getMealPlan' : IDL.Func([], [IDL.Opt(MealPlan)], ['query']),
    'getNutritionLog' : IDL.Func([], [NutritionLog], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logNutrition' : IDL.Func([NutritionLog], [], []),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMealPlan' : IDL.Func([MealPlan], [], []),
    'toggleGroceryItemChecked' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };